services:
  ai-service:
    build: ./healthcare-backend/backend-python
    restart: unless-stopped
    env_file:
      - ./healthcare-backend/backend-python/.env
    ports:
      - "8001:8001"

  backend:
    build: ./healthcare-backend/backend-spring
    restart: unless-stopped
    depends_on:
      - ai-service
    environment:
      PYTHON_SERVICE_URL: http://ai-service:8001
    ports:
      - "8081:8081"

  frontend:
    build: ./healthcare-ui
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"